info:
  component: Config Server
spring:
  application:
    name: configserver
  rabbitmq:
      host: mybroker.com
      port: 5672
      username: user
      password: secret
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/markWord/
          searchPaths: foo,bar*
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/markWord/config-repo


server:
  port: 8888
management:
  context_path: /admin
